version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-phonebook
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: phonebookdb
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: phonebook-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/phonebookdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    build: ./frontend
    container_name: phonebook-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
